from .apontamentos import ApontamentosView
from .atributos import AtributosView
from .estoque import EstoqueView
from .estrutura_produto import EstruturaProdutoView
from .grupo_recurso import GrupoRecursoView
from .item import ItemView
from .lista_materiais import ListaMateriaisView
from .manutencao import ManutencaoView
from .ordem_compra import OrdemCompraView
from .ordem_producao import OrdemProducaoView
from .recurso import RecursoView
from .roteiro_fabricacao import RoteiroFabricacaoView
from .unidade_fabril import UnidadeFabrilView
from .exportacao_erp import ExportacaoERPView
